---
# tasks file for aeeaan.repo-aeeaan
- block:
    - name: install aeeaan repo key
      rpm_key:
        key: https://aeeaan.github.io/al2023/RPM-GPG-KEY
        state: present

    - name: install aeeaan repo
      template:
        src: aeeaan.repo.j2
        dest: /etc/yum.repos.d/aeeaan.repo
        owner: root
        group: root
        mode: 0644

  when: repo_aeeaan_install
  tags:
    - repos
    - packages